import java.io.File

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
plugins {
    application
    eclipse
    java
    //https://github.com/JetBrains/gradle-intellij-plugin
    //id("org.jetbrains.intellij") version "1.1.4"
    //https://github.com/esoco/gwt-gradle-plugin
    //id("de.esoco.gwt-lib") version "1.1.0"
    //https://github.com/ascendtech/gwt-gradle
    id("us.ascendtech.gwt.modern") version "0.5.4"
}

dependencies {
    runtimeClasspath("com.google.gwt:gwt-user:2.9.0")
    runtimeClasspath("com.google.gwt:gwt-dev:2.9.0")
}

//
//buildscript {
//    repositories {
//        mavenCentral()
//    }
//    dependencies {
//        classpath("org.wisepersist:gwt-gradle-plugin:1.1.12")
//    }
//}
//
//apply(plugin = "gwt")

repositories {
    mavenCentral()
}

//gwt {
//    modules = listOf("org.adligo.gwt_node_hw.GwtNodeHw")
//}
task<Exec>("gwt") {
    println("building gwt")
    commandLine("java", "--version")
    println("jars;")
    //https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/Configuration.html
    val impl = configurations.getByName("runtimeClasspath")
    println("implementation is " + impl.getAllDependencies())
    val all = ArrayList<String>()
    all.add("src/main/java")
    all.add("build/classes/java/main")
    for (c in configurations.getByName("runtimeClasspath").getAllDependencies()) {
      println("hey " + c)
        //Set<File>
       val files = impl.files(c)
        //println("files " + files)
        for (file in files) {
            all.add(file.getAbsolutePath())
        }
    }
    var cp = ""
    var first = true
    for (fileName in all) {
        if (!first) {
            cp = cp + ":"//FIX ME this is Mac specific
        } else {
            first = false
        }
        cp = cp + fileName
    }
    //println("classpath is " + cp)
    commandLine("java", "-cp", cp, "com.google.gwt.dev.Compiler", "-style","DETAILED", "org.adligo.gwt_node_hw.GwtNodeHw")
}

application {
    mainClass.set("com.google.gwt.dev.Compiler")
}