/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
plugins {
    application
    eclipse
    java
    //https://github.com/JetBrains/gradle-intellij-plugin
    //id("org.jetbrains.intellij") version "1.1.4"
    //https://github.com/esoco/gwt-gradle-plugin
    //id("de.esoco.gwt-lib") version "1.1.0"
    //https://github.com/ascendtech/gwt-gradle
    id("us.ascendtech.gwt.modern") version "0.5.4"
}

dependencies {
    implementation("com.google.gwt:gwt-user:2.9.0")
    runtimeClasspath("com.google.gwt:gwt-dev:2.9.0")
}

//
//buildscript {
//    repositories {
//        mavenCentral()
//    }
//    dependencies {
//        classpath("org.wisepersist:gwt-gradle-plugin:1.1.12")
//    }
//}
//
//apply(plugin = "gwt")

repositories {
    mavenCentral()
}

gwt {
    modules = listOf("org.adligo.gwt_node_hw.GwtNodeHw")
}
//task<Exec>("gwt") {
//    println("building gwt")
//    commandLine("java", "--version")
//    println("jars;")
//    val impl = configurations.getByName("runtimeClasspath")
//    println("implementation is " + impl.getAllDependencies())
//    for (c in configurations.getByName("runtimeClasspath").getAllDependencies()) {
//      println("hey " + c)
//       val files = impl.files(c)
//        println("files " + files)
//    }
//}

application {
    mainClass.set("com.google.gwt.dev.Compiler")
}